"""initial schema

Revision ID: e07449b1d263
Revises: 
Create Date: 2026-05-31 21:31:39.828411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07449b1d263'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('hackathon', 'certification', 'internship', 'competition', 'other', name='opportunitytype'), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('deadline_status', sa.String(), nullable=True),
    sa.Column('verified_live', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_url'), 'opportunities', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('interests', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('why_relevant', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_opportunities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_opportunities_url'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###
